### ISSUE TITLE
wow

### ISSUE THREAD

**Issue by hakuei0115** [ZhangZJ0906/written-examination_biggo#1]
What is this project.

**Comment by ZhangZJ0906** [comment]
實習公司筆試

Borui.Lin ***@***.***>於 2024年8月23日 週五，00:42寫道：

**Comment by hakuei0115** [comment]
代表他可以看到我發的issues吧

**Comment by ZhangZJ0906** [comment]
沒錯現在發的他都看的到我也不知道怎麼關🤣

Borui.Lin ***@***.***>於 2024年8月23日 週五，00:47寫道：

**Comment by hakuei0115** [comment]
![image](https://github.com/user-attachments/assets/3335faac-f213-4e9c-9013-310f79dd5104)

**Comment by ZhangZJ0906** [comment]
Haha, thanks!

Borui.Lin ***@***.***>於 2024年8月23日 週五，00:50寫道：
